### ISSUE TITLE
add a tabulator component

### ISSUE THREAD

**Issue by martindemello** [arkadiyk/surface_rich_components#5]
tabulator (http://www.tabulator.info/) would be a great basis for a rich component. I'm trying to get it integrated into an app right now, if there's any interest I will try to pull it out into a standalone component when I'm done and contribute it here.

**Comment by arkadiyk** [comment]
The problem with all JS data components in the server rendered app is how to pass data into the JS component. It's possible but not practical for large amount of data..

This is the reason I cannot use any of the JS dropdowns like Select2 in this lib. 

The approach I am taking is to keep all the data management like retrieval,  pagination, etc on the server side. JS part is to add rich functionality to server rendered data. The server provides hooks for JS using HTML `data-` attributes. 

So unfortunately Tabulator doesn't really fit this concept. There are some old JS libs which add dynamic functionality to an HTML table. Maybe one day I will add something similar to this lib. Something like https://surface-ui.org/slots section "Binding slot arguments to generators" but with sorting, pagination, etc.

**Comment by martindemello** [comment]
makes sense! it would be neat to see a good table component someday, though i agree that tabulator does not fit your design goals.
